version: '3.7'

services:
  front-dev-house:
    depends_on:
      - api-dev-house
    build:
      context: ./front-dev-house/dev-house
      dockerfile: Dockerfile
    environment:
       - API_URL=http://app-elastic-env.eba-anym2kbb.us-east-1.elasticbeanstalk.com:8080/
    ports:
      - "80:80"
    networks:
      - app-network

  api-dev-house:
    depends_on:
      - mongodb
    build:
      context: ./api-Dev-House
      dockerfile: Dockerfile
    environment:
       - API_URL=http://app-elastic-env.eba-anym2kbb.us-east-1.elasticbeanstalk.com:8080/
    ports:
      - "3333:3333"
    volumes:
      - uploads:/user/uploads
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: "mongo"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
  uploads:
