version: '3.8'
services:
  app:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: "mongo"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
volumes:
  db: